sudo: required
services:
  - docker

before_install:
  - docker build -t heunsig/practice-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true heunsig/practice-docker-react npm run test
  
